package: skibbitools
version: '24.2.22'
author: 'KLXM Crossmedia'
supportpage: https://klxm.de
info: 'SkibbiTools'
load: late
requires:
    redaxo: '>=5.15.1'
    php: '>=8.1'
    packages:
         navigation_array: '>=1.0.0'
         mform: '>=7.0.0-dev'
         uikit_collection: '>=4.0.0-dev'
         maintenance: '>=3.0.0-dev'
